### ISSUE TITLE
Issues with certain instances

### ISSUE THREAD

**Issue by ghost** [compufox/tootapult#4]
I attempted to use this tool for Gab, and I receive an error every time I give the necessary authentication token, I tested this for mastadon.social and encountered no issues.

When attempting to use the gab.com mastadon-url, and after entering the neccesary access-token:

```
<ERROR> [01:37:12] tootapult tootapult.lisp (main fun24) -
  encountered error: TOOTAPULT::E: #<SIMPLE-ERROR "Invalid URI scheme: ~S" {10049678D3}>
```

Any ideas of where to possibly start to fix this?

**Comment by compufox** [comment]
I don't really see an issue here.
